# Generated by Django 6.1.1 on 2026-09-17 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('competitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, unique=True)),
                ('platform', models.CharField(blank=True, choices=[('PLAYSTATION', 'PlayStation'), ('XBOX', 'Xbox'), ('PC', 'PC')], max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='competitions.country')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'ordering': ['nickname'],
            },
        ),
        migrations.CreateModel(
            name='PlayerClubHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField()),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('club_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_history', to='clubs.clubseason')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_history', to='players.player')),
            ],
            options={
                'verbose_name': 'Historial de Club del Jugador',
                'verbose_name_plural': 'Historiales de Club de Jugadores',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerIdentityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('changed_at', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nickname_changes', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_history', to='players.player')),
            ],
            options={
                'verbose_name': 'Historial de Identidad',
                'verbose_name_plural': 'Historiales de Identidad',
                'ordering': ['-changed_at'],
            },
        ),
    ]
