# Generated by Django 6.1.1 on 2026-09-23 20:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('players', '0002_player_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_club_season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='clubs.clubseason')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='players.player')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_transfers', to=settings.AUTH_USER_MODEL)),
                ('to_club_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='clubs.clubseason')),
            ],
            options={
                'verbose_name': 'Transferencia',
                'verbose_name_plural': 'Transferencias',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
