# Generated by Django 6.1.1 on 2026-09-17 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('competitions', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matchday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchdays', to='competitions.division')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchdays', to='competitions.season')),
            ],
            options={
                'verbose_name': 'Jornada',
                'verbose_name_plural': 'Jornadas',
                'ordering': ['season', 'division', 'number'],
                'unique_together': {('season', 'division', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_goals', models.IntegerField(blank=True, null=True)),
                ('away_goals', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programado'), ('IN_PROGRESS', 'En Juego'), ('FINISHED', 'Finalizado'), ('POSTPONED', 'Aplazado'), ('CANCELLED', 'Cancelado')], default='SCHEDULED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('away_club_season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='clubs.clubseason')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='competitions.division')),
                ('home_club_season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='clubs.clubseason')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='competitions.season')),
                ('matchday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='matches.matchday')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['date', 'time', 'matchday__number'],
            },
        ),
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('is_starter', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_players', to='clubs.clubseason')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_players', to='matches.match')),
                ('player', models.ForeignKey(blank=True, help_text='NULL represents a BOT', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_participations', to='players.player')),
            ],
            options={
                'verbose_name': 'Jugador del Partido',
                'verbose_name_plural': 'Jugadores del Partido',
                'ordering': ['match', 'club_season', '-is_starter'],
            },
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('GOAL', 'Gol'), ('OWN_GOAL', 'Gol en Contra'), ('ASSIST', 'Asistencia'), ('YELLOW_CARD', 'Tarjeta Amarilla'), ('RED_CARD', 'Tarjeta Roja'), ('MVP', 'MVP')], max_length=20)),
                ('minute', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matches.match')),
                ('match_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matches.matchplayer')),
            ],
            options={
                'verbose_name': 'Evento del Partido',
                'verbose_name_plural': 'Eventos del Partido',
                'ordering': ['match', 'minute', 'event_type'],
            },
        ),
    ]
