# Generated by Django 6.1.1 on 2026-09-24 04:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchplayer',
            options={'ordering': ['id'], 'verbose_name': 'Jugador del Partido', 'verbose_name_plural': 'Jugadores del Partido'},
        ),
        migrations.CreateModel(
            name='MatchPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('goals', models.PositiveSmallIntegerField(default=0)),
                ('assists', models.PositiveSmallIntegerField(default=0)),
                ('shots', models.PositiveSmallIntegerField(default=0)),
                ('shot_accuracy_pct', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('passes', models.PositiveSmallIntegerField(default=0)),
                ('pass_accuracy_pct', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('dribbles', models.PositiveSmallIntegerField(default=0)),
                ('dribble_success_pct', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('tackles', models.PositiveSmallIntegerField(default=0)),
                ('tackle_success_pct', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('offsides', models.PositiveSmallIntegerField(default=0)),
                ('fouls', models.PositiveSmallIntegerField(default=0)),
                ('possession_won', models.PositiveSmallIntegerField(default=0)),
                ('possession_lost', models.PositiveSmallIntegerField(default=0)),
                ('minutes_played', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(130)])),
                ('distance_km', models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999.9)])),
                ('sprint_distance_km', models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999.9)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='matches.matchplayer')),
            ],
            options={
                'verbose_name': 'Rendimiento del Partido',
                'verbose_name_plural': 'Rendimientos de Partidos',
                'ordering': ['id'],
            },
        ),
    ]
