# Generated by Django 6.1.1 on 2026-09-17 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('clubs', '0001_initial'),
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubadmin',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrators', to='clubs.club'),
        ),
        migrations.AddField(
            model_name='clubadmin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_administrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leagueadmin',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrators', to='competitions.league'),
        ),
        migrations.AddField(
            model_name='leagueadmin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_administrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='clubadmin',
            unique_together={('user', 'club')},
        ),
        migrations.AlterUniqueTogether(
            name='leagueadmin',
            unique_together={('user', 'league')},
        ),
    ]
