# Generated by Django 6.1.1 on 2026-09-17 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('format_type', models.CharField(choices=[('ROUND_ROBIN', 'Liga (Todos contra todos)'), ('DOUBLE_ROUND_ROBIN', 'Liga doble (Ida y vuelta)'), ('CUSTOM', 'Personalizado')], max_length=20)),
                ('has_playoffs', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Formato de Competición',
                'verbose_name_plural': 'Formatos de Competición',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='ISO 3166-1 alpha-2', max_length=2, unique=True)),
                ('flag_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Juego',
                'verbose_name_plural': 'Juegos',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='competitions.country')),
            ],
            options={
                'verbose_name': 'Liga',
                'verbose_name_plural': 'Ligas',
                'ordering': ['country', 'name'],
                'unique_together': {('name', 'country')},
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UPCOMING', 'Próxima'), ('ACTIVE', 'Activa'), ('FINISHED', 'Finalizada')], default='UPCOMING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seasons', to='competitions.competitionformat')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='competitions.game')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='competitions.league')),
            ],
            options={
                'verbose_name': 'Temporada',
                'verbose_name_plural': 'Temporadas',
                'ordering': ['league', '-created_at'],
                'unique_together': {('league', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(help_text='Order within the season (1=first, 2=second, etc.)')),
                ('max_clubs', models.IntegerField(default=20)),
                ('playoff_zone_start', models.IntegerField(blank=True, null=True)),
                ('playoff_zone_end', models.IntegerField(blank=True, null=True)),
                ('promotion_zone_start', models.IntegerField(blank=True, null=True)),
                ('promotion_zone_end', models.IntegerField(blank=True, null=True)),
                ('relegation_zone_start', models.IntegerField(blank=True, null=True)),
                ('relegation_zone_end', models.IntegerField(blank=True, null=True)),
                ('has_relegation', models.BooleanField(default=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='competitions.season')),
            ],
            options={
                'verbose_name': 'División',
                'verbose_name_plural': 'Divisiones',
                'ordering': ['season', 'order'],
                'unique_together': {('season', 'order')},
            },
        ),
    ]
