# Generated by Django 6.1.1 on 2026-09-17 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.IntegerField(default=0)),
                ('won', models.IntegerField(default=0)),
                ('drawn', models.IntegerField(default=0)),
                ('lost', models.IntegerField(default=0)),
                ('goals_for', models.IntegerField(default=0)),
                ('goals_against', models.IntegerField(default=0)),
                ('goal_difference', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='clubs.clubseason')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='competitions.division')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='competitions.season')),
            ],
            options={
                'verbose_name': 'Posición',
                'verbose_name_plural': 'Tabla de Posiciones',
                'ordering': ['season', 'division', 'position'],
                'unique_together': {('season', 'division', 'club_season')},
            },
        ),
    ]
