# Generated by Django 6.1.1 on 2026-09-17 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clubs/logos/')),
                ('founded_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='competitions.country')),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClubTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_type', models.CharField(choices=[('CHAMPION', 'Campeón'), ('RUNNER_UP', 'Subcampeón'), ('PLAYOFF_WINNER', 'Ganador del Reducido'), ('PROMOTION_WINNER', 'Ganador de Promoción')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('awarded_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('awarded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_titles', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='clubs.club')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_titles', to='competitions.division')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_titles', to='competitions.season')),
            ],
            options={
                'verbose_name': 'Título de Club',
                'verbose_name_plural': 'Títulos de Clubes',
                'ordering': ['-awarded_at'],
            },
        ),
        migrations.CreateModel(
            name='ClubSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('RELEGATED', 'Descendido'), ('PROMOTED', 'Ascendido'), ('WITHDRAWN', 'Retirado')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='clubs.club')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_seasons', to='competitions.division')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_seasons', to='competitions.season')),
            ],
            options={
                'verbose_name': 'Club por Temporada',
                'verbose_name_plural': 'Clubes por Temporada',
                'ordering': ['season', 'division', 'club__name'],
                'unique_together': {('club', 'season')},
            },
        ),
    ]
